# Generated by Django 5.0.1 on 2024-02-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='entry_date',
            new_name='date_joined',
        ),
    ]
